"""empty message

Revision ID: 717927db0c7
Revises: 431a5a6e0b2d
Create Date: 2015-03-02 15:22:30.830804

"""

# revision identifiers, used by Alembic.
revision = '717927db0c7'
down_revision = '431a5a6e0b2d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carddata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_number', sa.String(length=32), nullable=True),
    sa.Column('di_user', sa.Integer(), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('id_card_reader', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_carddata')
    )
    op.create_index('ix_carddata_card_number', 'carddata', ['card_number'], unique=False)
    op.create_index('ix_carddata_di_user', 'carddata', ['di_user'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_carddata_di_user', table_name='carddata')
    op.drop_index('ix_carddata_card_number', table_name='carddata')
    op.drop_table('carddata')
    ### end Alembic commands ###
